# Generated by Django 6.0.3 on 2026-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoute', models.CharField()),
                ('submited_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
